<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>HlslLsp.VisualStudio</RootNamespace>
    <AssemblyName>HlslLsp.VisualStudio.Classification</AssemblyName>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.ComponentModel.Composition" />
    <PackageReference Include="Microsoft.VisualStudio.SDK"
                      Version="17.14.40265"
                      ExcludeAssets="runtime" />
  </ItemGroup>
</Project>
