import "./compilationInfo.test";
import "./configuration.test";
import "./lifecycle.test";
import "./memoryLayout.test";
import "./preprocessorExplorer.test";
import "./resourceBindings.test";
import "./runtime.test";
import "./settingsSynchronizer.test";
import "./watchers.test";
